version: '3.9'

services:
  backend:
    build: ./backend/
    volumes:
      - ./backend/src:/var/www
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/src:/app
    command: 'yarn dev'
    ports:
      - 3000:3000
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./backend/src:/var/www
    depends_on:
      - backend
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
volumes:
  mysql_volume: